
/*!
** @file   ObjDict.h
** @author CAN Festival -- NNP
** @date   OD File produced: 2011-05-17 13:08:22.997000
**
** @brief This file is generated by the NNP Tool -- Object Dictionary Editor, as 
** originally developed by CAN Festival and modified by the NNP Team. 
** Specific contents are detailed in Object Dictionary Template.
** Editor modification: 4/29/2010 -- rev 1.0.0 
**
** This ObjDict.h file is generated from BiopotentialSensor2ch.odnn
** 
*/  

/*This object dictionary file should only be modified by the Object Dictionary Editor */

#ifndef OBJDICT_H
#define OBJDICT_H

#include "data.h"

#define APP_REV 138

/* Prototypes of function provided by object dictionnary */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value);
const indextable * ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data ObjDict_Data;
extern UNS32 ObjDict_obj1018_Serial_Number;
extern UNS8 SyncTiming[23];
extern UNS8 SyncInterval;

extern UNS8 clockRate;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 Control_ScriptStatus;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS8 Control_CurrentGroup;		/* Mapped at index 0x2001, subindex 0x02 */
extern UNS16 X_Network;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 Temperature;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS32 DateTime_Date;		/* Mapped at index 0x2004, subindex 0x01 */
extern UNS32 DateTime_Time;		/* Mapped at index 0x2004, subindex 0x02 */
extern UNS8 Status_modeSelect;		/* Mapped at index 0x2010, subindex 0x01 */
extern UNS8 Status_numTPDO;
extern UNS8 Status_numRPDO;
extern UNS8 Status_channelSelect;		/* Mapped at index 0x2010, subindex 0x02 */
extern UNS8 Status_profileSelect;		/* Mapped at index 0x2010, subindex 0x03 */
extern UNS8 Status_profileWrite;		/* Mapped at index 0x2010, subindex 0x04 */
extern UNS8 Status_NodeId;
extern UNS16 Status_TestValue;
extern UNS8 Status_TestValue8;
extern UNS8 Accelerometers[4];		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS8 AccelerometersFiltered[4];      /* Mapped at index 0x2011, subindex 0x01 */
extern INTEGER8 AccelerometersTilt[4];
extern UNS8 AccelerometerSettings;  /*0x2012*/
extern UNS32 AddressRequest;
extern UNS8 memorySelect;
extern UNS8 triggerReadMemory;
extern UNS8 writeByteMemory;
extern UNS8 statusByteMemory;
extern UNS8 ReadMemoryData[36];
extern UNS16 addressCounter;
extern UNS16 CAN_FormErrors;
extern UNS16 CAN_StuffErrors;
extern UNS16 CAN_BitErrors;
extern UNS16 CAN_OtherErrors;
extern UNS16 CAN_TotalErrors;
extern UNS16 CAN_Rx_ErrCounter;
extern UNS16 CAN_Tx_ErrCounter;
extern UNS16 CAN_Receive_BEI;
extern UNS16 CAN_Receive_Messages;
extern UNS16 CAN_Transmit_Messages;
extern UNS16 CAN_Interrupts_Off;
extern UNS16 RestoreList[11];
extern UNS8 DiagnosticsEnabled;
extern UNS8 Diagnostic_VIN;
extern UNS8 Diagnostic_VIC;
extern UNS8 Diagnostic_OFF1;
extern UNS8 Diagnostic_OFF2;
extern UNS8 Config_Module;		/* Mapped at index 0x3400, subindex 0x01 */
extern UNS8 Config_Shutdown;		/* Mapped at index 0x3400, subindex 0x02 */
extern INTEGER8 Chan1Data_Raw;		/* Mapped at index 0x3410, subindex 0x01 */
extern INTEGER8 Chan1Data_ADC;
extern UNS8 Chan1Config_IgnoreCount;		/* Mapped at index 0x3411, subindex 0x01 */
extern UNS8 Chan1Config_Gain;		/* Mapped at index 0x3411, subindex 0x02 */
extern UNS8 Chan1Config_AverageDepth;		/* Mapped at index 0x3411, subindex 0x07 */
extern UNS8 Chan1Config_Threshold_ZX;		/* Mapped at index 0x3411, subindex 0x09 */ 
extern UNS8 Chan1Config_Threshold_SSC;		/* Mapped at index 0x3411, subindex 0x0A */ 
extern UNS8 Chan1Config_Gain_MAV;
extern UNS8 Chan1Config_Gain_MV;
extern UNS8 Chan1Config_Gain_WFL;
extern UNS8 Chan1FeatureSelect;
extern UNS8 Chan1Features_MeanAbsValue;		/* Mapped at index 0x3412, subindex 0x01 */ 
extern INTEGER8 Chan1Features_MeanValue;		/* Mapped at index 0x3412, subindex 0x02 */
extern UNS8 Chan1Features_ZeroCrossing;		/* Mapped at index 0x3412, subindex 0x03 */
extern UNS8 Chan1Features_SlopeSignChange;		/* Mapped at index 0x3412, subindex 0x04 */
extern UNS8 Chan1Features_WaveFormLength;		/* Mapped at index 0x3412, subindex 0x05 */
extern INTEGER8 Chan2Data_Raw;	
extern INTEGER8 Chan2Data_ADC;/* Mapped at index 0x3510, subindex 0x01 */
extern UNS8 Chan2Config_IgnoreCount;		/* Mapped at index 0x3511, subindex 0x01 */
extern UNS8 Chan2Config_Gain;		/* Mapped at index 0x3511, subindex 0x02 */
extern UNS8 Chan2Config_AverageDepth;		/* Mapped at index 0x3511, subindex 0x07 */
extern UNS8 Chan2Config_FixedWindowSize;		/* Mapped at index 0x3511, subindex 0x08 */ 
extern UNS8 Chan2Config_Threshold_ZX;		/* Mapped at index 0x3511, subindex 0x09 */ 
extern UNS8 Chan2Config_Threshold_SSC;		/* Mapped at index 0x3511, subindex 0x0A */ 
extern UNS8 Chan2Config_Gain_MAV;
extern UNS8 Chan2Config_Gain_MV;
extern UNS8 Chan2Config_Gain_WFL;
extern UNS8 Chan2FeatureSelect;
extern UNS8 Chan2Features_MeanAbsValue;		/* Mapped at index 0x3512, subindex 0x01 */ 
extern INTEGER8 Chan2Features_MeanValue;		/* Mapped at index 0x3512, subindex 0x02 */
extern UNS8 Chan2Features_ZeroCrossing;		/* Mapped at index 0x3512, subindex 0x03 */
extern UNS8 Chan2Features_SlopeSignChange;		/* Mapped at index 0x3512, subindex 0x04 */
extern UNS8 Chan2Features_WaveFormLength;		/* Mapped at index 0x3512, subindex 0x05 */

#endif // OBJDICT_H
