
/*!
** @file   ObjDict.c
** @author CAN Festival -- NNP
** @date   OD File produced: 2011-05-17 13:08:22.997000
**
** @brief This file is generated by the NNP Tool -- Object Dictionary Editor, as 
** originally developed by CAN Festival and modified by the NNP Team. 
** Specific contents are detailed in Object Dictionary Template.
** Editor modification: 4/29/2010 -- rev 1.0.0 
**
** This ObjDict.c file is generated from BiopotentialSensor2ch.odnn
** 
*/  

/*This object dictionary file should only be modified by the Object Dictionary Editor */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

UNS8 clockRate = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 Control_ScriptStatus = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS8 Control_CurrentGroup = 0x0;		/* Mapped at index 0x2001, subindex 0x02 */
UNS16 X_Network = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Temperature = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS32 DateTime_Date = 0x0;		/* Mapped at index 0x2004, subindex 0x01 */
UNS32 DateTime_Time = 0x0;		/* Mapped at index 0x2004, subindex 0x02 */
UNS8 Status_modeSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x01 */
UNS8 Status_numTPDO = 4;
UNS8 Status_numRPDO = 4;
UNS8 Status_channelSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x02 */
UNS8 Status_profileSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x03 */
UNS8 Status_profileWrite = 0x0;		/* Mapped at index 0x2010, subindex 0x04 */
UNS8 Status_NodeId = 0x05;
UNS16 Status_TestValue = 0x00;
UNS8 Status_TestValue8 = 0x00;
UNS8 Accelerometers[4] = 
{ 0x00,  0x00,  0x00, 0x00 };		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 AccelerometersFiltered[4] = 
{ 0x00,  0x00,  0x00, 0x00 };         /* Mapped at index 0x2011, subindex 0x01 */
INTEGER8 AccelerometersTilt[4] = 
{ 0x00,  0x00,  0x00, 0x00 };         /* Mapped at index 0x2011, subindex 0x01 */
UNS8 AccelerometerSettings = 0;  /*0x2012*/
UNS32 AddressRequest = 0x00000000;
UNS8 memorySelect = 0x00;
UNS8 triggerReadMemory = 0x00;
UNS8 writeByteMemory = 0x00;
UNS8 statusByteMemory = 0x00;
UNS8 ReadMemoryData[36] = 
{ 0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00,  0x00,  0x00,  0x00,\
  0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00,  0x00,  0x00,  0x00, \
  0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00 , 0x00,  0x00,  0x00 };
UNS16 addressCounter = 0x0000;
UNS16 CAN_FormErrors = 0x00;
UNS16 CAN_StuffErrors = 0x00;
UNS16 CAN_BitErrors = 0x00;
UNS16 CAN_OtherErrors = 0x00;
UNS16 CAN_TotalErrors = 0x00;
UNS16 CAN_Rx_ErrCounter = 0x00;
UNS16 CAN_Tx_ErrCounter = 0x00;
UNS16 CAN_Receive_BEI = 0x00;
UNS16 CAN_Receive_Messages = 0x00;
UNS16 CAN_Transmit_Messages = 0x00;
UNS16 CAN_Interrupts_Off = 0x00;
UNS8 DiagnosticsEnabled = 4;
UNS8 Diagnostic_VIN = 0x00;
UNS8 Diagnostic_VIC = 0x00;
UNS8 Diagnostic_OFF1 = 0x00;
UNS8 Diagnostic_OFF2 = 0x00;
UNS8 Config_Module = 0x0;		/* Mapped at index 0x3400, subindex 0x01 */
UNS8 Config_Shutdown = 0x0;		/* Mapped at index 0x3400, subindex 0x02 */
INTEGER8 Chan1Data_Raw = 0x0;		/* Mapped at index 0x3410, subindex 0x01 */
INTEGER8 Chan1Data_ADC = 0x0;
UNS8 Chan1Config_Gain = 0x0A;		/* Mapped at index 0x3411, subindex 0x02 */	/* Mapped at index 0x3411, subindex 0x03 */
UNS8 Chan1Config_AverageDepth = 0x1;		/* Mapped at index 0x3411, subindex 0x07 */
UNS8 Chan1Config_Threshold_ZX =0x0;              /* Mapped at index 0x3411, subindex 0x09 */ 
UNS8 Chan1Config_Threshold_SSC =0x0;              /* Mapped at index 0x3411, subindex 0x0A */
UNS8 Chan1Config_Gain_MAV = 0x02;
UNS8 Chan1Config_Gain_MV = 0x02;
UNS8 Chan1Config_Gain_WFL = 0x02;
UNS8 Chan1FeatureSelect=0x45;
UNS8 Chan1Features_MeanAbsValue = 0x0;		/* Mapped at index 0x3412, subindex 0x01 */ 
INTEGER8 Chan1Features_MeanValue = 0x0;		/* Mapped at index 0x3412, subindex 0x02 */ 
UNS8 Chan1Features_ZeroCrossing = 0x0;		/* Mapped at index 0x3412, subindex 0x03 */
UNS8 Chan1Features_SlopeSignChange = 0x0;		/* Mapped at index 0x3412, subindex 0x04 */
UNS8 Chan1Features_WaveFormLength = 0x0;		/* Mapped at index 0x3412, subindex 0x05 */
INTEGER8 Chan2Data_Raw = 0x0;		/* Mapped at index 0x3510, subindex 0x01 */
INTEGER8 Chan2Data_ADC = 0x0;
UNS8 Chan2Config_Gain = 0x0A;		/* Mapped at index 0x3511, subindex 0x02 */
UNS8 Chan2Config_AverageDepth = 0x1;		/* Mapped at index 0x3511, subindex 0x07 */
UNS8 Chan2Config_Threshold_ZX =0x0;              /* Mapped at index 0x3511, subindex 0x09 */ 
UNS8 Chan2Config_Threshold_SSC =0x0;              /* Mapped at index 0x3511, subindex 0x0A */
UNS8 Chan2Config_Gain_MAV = 0x02;
UNS8 Chan2Config_Gain_MV = 0x02;
UNS8 Chan2Config_Gain_WFL = 0x02;
UNS8 Chan2FeatureSelect=0x45;
UNS8 Chan2Features_MeanAbsValue = 0x0;		/* Mapped at index 0x3512, subindex 0x01 */  
INTEGER8 Chan2Features_MeanValue = 0x0;		/* Mapped at index 0x3512, subindex 0x02 */  
UNS8 Chan2Features_ZeroCrossing = 0x0;		/* Mapped at index 0x3512, subindex 0x03 */
UNS8 Chan2Features_SlopeSignChange = 0x0;		/* Mapped at index 0x3512, subindex 0x04 */ 
UNS8 Chan2Features_WaveFormLength = 0x0;		/* Mapped at index 0x3512, subindex 0x05 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict_bDeviceNodeId = 5;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDict_iam_a_slave = 1;

TIMER_HANDLE ObjDict_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict_obj1000 = 0x53504E4E;	/* 1397771854 */
                    const subindex ObjDict_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict_obj1001 = 0x0;	/* 0 */
                    const subindex ObjDict_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDict_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 ObjDict_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 ObjDict_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    INTEGER8 ObjDict_obj1008[28] = "2ch Biopotential Sensor BP-2";
                    const subindex ObjDict_Index1008[] = 
                     {
                       { RO, visible_string, 28, (void*)&ObjDict_obj1008 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDict_obj1014 = 0x80 + 0x03;  

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 ObjDict_highestSubIndex_obj1016 = 0;
                    UNS32 ObjDict_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 ObjDict_obj1017 = 2311;	/* 2311 */ 
                    ODCallback_t ObjDict_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    const subindex ObjDict_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    INTEGER8 ObjDict_obj1018_Vendor_ID[10] = "NNPS";
                    UNS8 ObjDict_obj1018_Product_Code = 0x5;	/* 5 */
                    UNS32 ObjDict_obj1018_Revision_Number = APP_REV;	/* 20 */
                    UNS32 ObjDict_obj1018_Serial_Number = 0x2545;	/* 9044 */
                    const subindex ObjDict_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1018 },
                       { RO, visible_string, 10, (void*)&ObjDict_obj1018_Vendor_ID },
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x603;
                    UNS32 ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x583;
                    const subindex ObjDict_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1400_Source_Address = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1400_Event_Timer = 0x0;	/* 0 */
                    const subindex ObjDict_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1400_Source_Address },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1400_Event_Timer }
                     };


/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    const subindex ObjDict_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1800_COB_ID_used_by_PDO = 0x185;	/*JML*//* 387 */
                    UNS8 ObjDict_obj1800_Transmission_Type = 0xFD;	/*JML*//* 0 */
                    UNS16 ObjDict_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1800_Event_Timer }
                     };


/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    
                    const subindex ObjDict_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[7] }
                     };

/* index 0x2000 :   Mapped variable Clock */
                    UNS8 ObjDict_highestSubIndex_obj2000 = 1; /* number of subindex - 1*/
                    ODCallback_t Clock_callbacks[] = 
                     {
                       NULL,
                       NULL
                     };
                    const subindex ObjDict_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2000 },
                       { RW, uint8, sizeof (UNS8), (void*)&clockRate }
                     };

/* index 0x2001 :   Mapped variable Control */
                    UNS8 ObjDict_highestSubIndex_obj2001 = 2; /* number of subindex - 1*/
                    const subindex ObjDict_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_ScriptStatus },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_CurrentGroup }
                     };

/* index 0x2002 :   Mapped variable X-Network */
                    UNS8 ObjDict_highestSubIndex_obj2002 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2002 },
                       { RW, uint16, sizeof (UNS16), (void*)&X_Network }
                     };

/* index 0x2003 :   Mapped variable Temperature */
                    UNS8 ObjDict_highestSubIndex_obj2003 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2003 },
                       { RO, uint16, sizeof (UNS16), (void*)&Temperature }
                     };

/* index 0x2004 :   Mapped variable DateTime */
                    UNS8 ObjDict_highestSubIndex_obj2004 = 2; /* number of subindex - 1*/
                    const subindex ObjDict_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2004 },
                       { RW, uint32, sizeof (UNS32), (void*)&DateTime_Date },
                       { RW, uint32, sizeof (UNS32), (void*)&DateTime_Time }
                     };

/* index 0x2010 :   Mapped variable Status */
                    UNS8 ObjDict_highestSubIndex_obj2010 = 9; /* number of subindex - 1*/
                    const subindex ObjDict_Index2010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2010 },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_modeSelect },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_numTPDO },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_numRPDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_channelSelect },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_profileSelect },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_profileWrite },
                       { RW, uint16, sizeof (UNS16), (void*)&Status_TestValue },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_TestValue8 },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_NodeId }
                      
                     };

/* index 0x2011 :   Mapped variable Accelerometer Values */
                    UNS8 ObjDict_highestSubIndex_obj2011 = 3; /* number of subindex - 1*/
                    const subindex ObjDict_Index2011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2011 },
                       { RW, uint8, 4, (void*)&Accelerometers[0] },
                       { RW, uint8, 4, (void*) &AccelerometersFiltered[0] },
                       { RW, int8, 4, (void*) &AccelerometersTilt[0] }
                     };

/* index 0x2012 :   Mapped variable Accelerometer Settings */
                    UNS8 ObjDict_highestSubIndex_obj2012 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2012[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2012 },
                       { RW, uint8, sizeof (UNS8), (void*) &AccelerometerSettings }
                     };

/* index 0x2020 :   Mapped variable RecordTransfer */
                    UNS8 ObjDict_highestSubIndex_obj2020 = 7;
                    const subindex ObjDict_Index2020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2020 },
                       { RW, uint32, sizeof (UNS32), (void*)&AddressRequest },    // 1
                       { RW, uint8, 36*sizeof (UNS8), (void*)&ReadMemoryData[0] },              // 19
                       { RW, uint32, sizeof (UNS32), (void*)&addressCounter },    // 21
                       { RW, uint8, sizeof (UNS8), (void*)&memorySelect },
                       { RW, uint8, sizeof (UNS8), (void*)&triggerReadMemory },
                       { RW, uint8, sizeof (UNS8), (void*)&writeByteMemory },
                       { RW, uint8, sizeof (UNS8), (void*)&statusByteMemory }
                      
                     };
                    
/* index 0x2500 :   Mapped variable CAN */
                    UNS8 ObjDict_highestSubIndex_obj2500 = 11; /* number of subindex - 1*/
                    const subindex ObjDict_Index2500[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2500 },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_TotalErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_BitErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_StuffErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_FormErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_OtherErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Rx_ErrCounter },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Tx_ErrCounter },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Receive_BEI },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Receive_Messages },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Transmit_Messages },
                       { RO, uint16, sizeof (UNS16),  (void*)&CAN_Interrupts_Off }
                     };
                    
/* index 0x2800 :   Mapped variable SyncTiming */
                    UNS8 ObjDict_highestSubIndex_obj2800 = 2; /* number of subindex - 1*/
                    UNS8 SyncTiming[23]=
                    {
                            // data are msecs after sync pulse.
                            // use 255 in unblank time to stop before 4 blanking slots.
                            
                            //dly  bl  unb  bl  unb ...
                            1,  255, 12,  20, 23,  40, 45,  60, 62,  255, 0,  	//chan1: delay, 5 x blkpairs ..,
                            1,  255, 12,  20, 23,  40, 45,  60, 62,  255, 0,  	//chan2: delay, 5 x blkpairs ..,
                            75							//calc (& sendpdo)
                    };
                    UNS8 SyncInterval = 1;  //<<JML
                     
                    const subindex ObjDict_Index2800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2800 },
                       { RW, uint8, 23, (void*)&SyncTiming[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&SyncInterval }
                     };
                    
/* index 0x2900 :   Mapped variable RestoreList */
                    UNS8 ObjDict_highestSubIndex_obj2900 = 1; /* number of subindex - 1*/
                    UNS16 RestoreList[11] = {  0x1400,/*RPDO Params*/\
                                               0x1600,/*RPDO Mapping*/\
                                               0x1800,/*TPDO Params*/\
                                               0x1A00,/*TPDO Mapping*/\
                                               0x2001, /*Control*/ \
                                               0x2012, /*Accel Settings*/\
                                               0x2800,/*SyncTiming*/ \
                                               0x3411, 0x3511,/*Chan Config*/\
                                               0x3412, 0x3512 /*Feature Select*/};
                     
                    const subindex ObjDict_Index2900[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2900 },
                       { RO, uint16, sizeof(RestoreList), (void*)&RestoreList[0] }
                     };
                    
/* index 0x3000 :   Mapped variable Diagnostics */
                    UNS8 ObjDict_highestSubIndex_obj3000 = 5; /* number of subindex - 1*/
                    const subindex ObjDict_Index3000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3000 },
                       { RW, uint8, sizeof (UNS8), (void*)&DiagnosticsEnabled },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VIN },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VIC },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_OFF1 },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_OFF2 }
                     };
                    
/* index 0x3400 :   Mapped variable Config */
                    UNS8 ObjDict_highestSubIndex_obj3400 = 2; /* number of subindex - 1*/
                    ODCallback_t Config_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index3400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3400 },
                       { RW, uint8, sizeof (UNS8), (void*)&Config_Module },
                       { RW, uint8, sizeof (UNS8), (void*)&Config_Shutdown }
                     };


/* index 0x3410 :   Mapped variable Chan1Data */
                    UNS8 ObjDict_highestSubIndex_obj3410 = 2; /* number of subindex - 1*/
                    const subindex ObjDict_Index3410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3410 },
                       { RO, uint8, sizeof (INTEGER8), (void*)&Chan1Data_Raw },
                       { RO, uint8, sizeof (INTEGER8), (void*)&Chan1Data_ADC }
                     };

/* index 0x3411 :   Mapped variable Chan1Config */
                    UNS8 ObjDict_highestSubIndex_obj3411 = 7; /* number of subindex - 1*/
                    const subindex ObjDict_Index3411[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3411 },                   
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_Gain },                     
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_AverageDepth },                     
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_Threshold_ZX }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_Threshold_SSC },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_Gain_MAV },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_Gain_MV },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Config_Gain_WFL }
                     };

/* index 0x3412 :   Mapped variable Chan1Features */
                    UNS8 ObjDict_highestSubIndex_obj3412 = 6; /* number of subindex - 1*/
                    const subindex ObjDict_Index3412[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3412 },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Features_MeanAbsValue }, 
                       { RW,  int8, sizeof (INTEGER8), (void*)&Chan1Features_MeanValue },   
                       { RW, uint8 , sizeof (UNS8), (void*)&Chan1Features_ZeroCrossing }, 
                       { RW, uint8 , sizeof (UNS8), (void*)&Chan1Features_SlopeSignChange }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1Features_WaveFormLength },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan1FeatureSelect }
                     };


/* index 0x3510 :   Mapped variable Chan2Data */
                    UNS8 ObjDict_highestSubIndex_obj3510 = 2; /* number of subindex - 1*/
                    const subindex ObjDict_Index3510[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3510 },
                       { RO, uint8, sizeof (INTEGER8), (void*)&Chan2Data_Raw },
                       { RO, uint8, sizeof (INTEGER8), (void*)&Chan2Data_ADC }
                                          
                     };

/* index 0x3511 :   Mapped variable Chan2Config */
                    UNS8 ObjDict_highestSubIndex_obj3511 = 7; /* number of subindex - 1*/
                    const subindex ObjDict_Index3511[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3511 },                       
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_Gain },                      
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_AverageDepth },                   
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_Threshold_ZX }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_Threshold_SSC }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_Gain_MAV },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_Gain_MV },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Config_Gain_WFL }
                       
                     };

/* index 0x3512 :   Mapped variable Chan2Features */
                    UNS8 ObjDict_highestSubIndex_obj3512 = 6; /* number of subindex - 1*/
                    const subindex ObjDict_Index3512[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3512 },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Features_MeanAbsValue }, 
                       { RW,  int8, sizeof (INTEGER8), (void*)&Chan2Features_MeanValue }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Features_ZeroCrossing }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Features_SlopeSignChange }, 
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2Features_WaveFormLength },
                       { RW, uint8, sizeof (UNS8), (void*)&Chan2FeatureSelect }
                     };



/**************************************************************************/
/* Declaration of variables                                       */
/**************************************************************************/

const indextable ObjDict_objdict[] = 
{
  { (subindex*)ObjDict_Index1000,sizeof(ObjDict_Index1000)/sizeof(ObjDict_Index1000[0]), 0x1000},
  { (subindex*)ObjDict_Index1001,sizeof(ObjDict_Index1001)/sizeof(ObjDict_Index1001[0]), 0x1001},
  { (subindex*)ObjDict_Index1008,sizeof(ObjDict_Index1008)/sizeof(ObjDict_Index1008[0]), 0x1008},
  { (subindex*)ObjDict_Index1017,sizeof(ObjDict_Index1017)/sizeof(ObjDict_Index1017[0]), 0x1017},
  { (subindex*)ObjDict_Index1018,sizeof(ObjDict_Index1018)/sizeof(ObjDict_Index1018[0]), 0x1018},
  { (subindex*)ObjDict_Index1200,sizeof(ObjDict_Index1200)/sizeof(ObjDict_Index1200[0]), 0x1200},
  { (subindex*)ObjDict_Index1400,sizeof(ObjDict_Index1400)/sizeof(ObjDict_Index1400[0]), 0x1400},
  { (subindex*)ObjDict_Index1600,sizeof(ObjDict_Index1600)/sizeof(ObjDict_Index1600[0]), 0x1600},
  { (subindex*)ObjDict_Index1800,sizeof(ObjDict_Index1800)/sizeof(ObjDict_Index1800[0]), 0x1800},
  { (subindex*)ObjDict_Index1A00,sizeof(ObjDict_Index1A00)/sizeof(ObjDict_Index1A00[0]), 0x1A00},
  { (subindex*)ObjDict_Index2000,sizeof(ObjDict_Index2000)/sizeof(ObjDict_Index2000[0]), 0x2000},
  { (subindex*)ObjDict_Index2001,sizeof(ObjDict_Index2001)/sizeof(ObjDict_Index2001[0]), 0x2001},
  { (subindex*)ObjDict_Index2002,sizeof(ObjDict_Index2002)/sizeof(ObjDict_Index2002[0]), 0x2002},
  { (subindex*)ObjDict_Index2003,sizeof(ObjDict_Index2003)/sizeof(ObjDict_Index2003[0]), 0x2003},
  { (subindex*)ObjDict_Index2004,sizeof(ObjDict_Index2004)/sizeof(ObjDict_Index2004[0]), 0x2004},
  { (subindex*)ObjDict_Index2010,sizeof(ObjDict_Index2010)/sizeof(ObjDict_Index2010[0]), 0x2010},
  { (subindex*)ObjDict_Index2011,sizeof(ObjDict_Index2011)/sizeof(ObjDict_Index2011[0]), 0x2011},
  { (subindex*)ObjDict_Index2012,sizeof(ObjDict_Index2012)/sizeof(ObjDict_Index2012[0]), 0x2012},
  { (subindex*)ObjDict_Index2020,sizeof(ObjDict_Index2500)/sizeof(ObjDict_Index2020[0]), 0x2020},
  { (subindex*)ObjDict_Index2500,sizeof(ObjDict_Index2500)/sizeof(ObjDict_Index2500[0]), 0x2500},
  { (subindex*)ObjDict_Index2800,sizeof(ObjDict_Index2800)/sizeof(ObjDict_Index2800[0]), 0x2800},
  { (subindex*)ObjDict_Index2900,sizeof(ObjDict_Index2900)/sizeof(ObjDict_Index2900[0]), 0x2900},
  { (subindex*)ObjDict_Index3000,sizeof(ObjDict_Index3000)/sizeof(ObjDict_Index3000[0]), 0x3000},
  { (subindex*)ObjDict_Index3400,sizeof(ObjDict_Index3400)/sizeof(ObjDict_Index3400[0]), 0x3400},
  { (subindex*)ObjDict_Index3410,sizeof(ObjDict_Index3410)/sizeof(ObjDict_Index3410[0]), 0x3410},
  { (subindex*)ObjDict_Index3411,sizeof(ObjDict_Index3411)/sizeof(ObjDict_Index3411[0]), 0x3411},
  { (subindex*)ObjDict_Index3412,sizeof(ObjDict_Index3412)/sizeof(ObjDict_Index3412[0]), 0x3412},
  { (subindex*)ObjDict_Index3510,sizeof(ObjDict_Index3510)/sizeof(ObjDict_Index3510[0]), 0x3510},
  { (subindex*)ObjDict_Index3511,sizeof(ObjDict_Index3511)/sizeof(ObjDict_Index3511[0]), 0x3511},
  { (subindex*)ObjDict_Index3512,sizeof(ObjDict_Index3512)/sizeof(ObjDict_Index3512[0]), 0x3512},
  
};

const indextable * ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1008: i = 2;break;
		case 0x1017: i = 3;*callbacks = ObjDict_Index1017_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1600: i = 7;break;
		case 0x1800: i = 8;*callbacks = ObjDict_Index1800_callbacks; break;
		case 0x1A00: i = 9;break;
		case 0x2000: i = 10;*callbacks = Clock_callbacks; break;
		case 0x2001: i = 11;break;
		case 0x2002: i = 12;break;
		case 0x2003: i = 13;break;
		case 0x2004: i = 14;break;
		case 0x2010: i = 15;break;
		case 0x2011: i = 16;break;
                case 0x2012: i = 17;break;
                case 0x2020: i = 18;break;
                case 0x2500: i = 19;break;
                case 0x2800: i = 20;break;
                case 0x2900: i = 21;break;
                case 0x3000: i = 22;break;
		case 0x3400: i = 23;break;
		case 0x3410: i = 24;break;
		case 0x3411: i = 25;break;
		case 0x3412: i = 26;break;	
		case 0x3510: i = 27;break;
		case 0x3511: i = 28;break;
		case 0x3512: i = 29;break;
		
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDict_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ObjDict_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index ObjDict_firstIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const quick_index ObjDict_lastIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  7, /* PDO_RCV_MAP */
  8, /* PDO_TRS */
  9 /* PDO_TRS_MAP */
};

const UNS16 ObjDict_ObjdictSize = sizeof(ObjDict_objdict)/sizeof(ObjDict_objdict[0]); 

CO_Data ObjDict_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict);

